"""
template_engine.py — Jinja2-based config file generator.
Renders NGINX configs, .env files, systemd units, and PM2 configs.
"""

from __future__ import annotations
from pathlib import Path
from typing import Any
from jinja2 import Environment, FileSystemLoader, BaseLoader, DictLoader


# ------------------------------------------------------------------ #
#  Inline templates (no filesystem required)                           #
# ------------------------------------------------------------------ #

NGINX_NODE = """\
server {
    listen 80;
    server_name {{ domain }};

    location / {
        proxy_pass http://localhost:{{ port | default(3000) }};
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
        proxy_read_timeout 300s;
        proxy_connect_timeout 75s;
    }

{% if static_dir is defined %}
    location /static/ {
        alias {{ static_dir }};
        expires 30d;
        add_header Cache-Control "public, immutable";
    }
{% endif %}

    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
}
"""

NGINX_LARAVEL = """\
server {
    listen 80;
    server_name {{ domain }};
    root {{ project_path }}/public;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/var/run/php/php{{ php_version | default('8.2') }}-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }

    client_max_body_size 64M;
    fastcgi_read_timeout 300;
}
"""

NGINX_STATIC = """\
server {
    listen 80;
    server_name {{ domain }};
    root {{ project_path }};
    index index.html index.htm;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Gzip compression
    gzip on;
    gzip_vary on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml text/javascript;

    # Cache static assets
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}
"""

PM2_CONFIG = """\
module.exports = {
  apps: [{
    name: '{{ app_name }}',
    script: '{{ script | default("npm") }}',
    args: '{{ args | default("run start") }}',
    cwd: '{{ project_path }}',
    instances: {{ instances | default(1) }},
    autorestart: true,
    watch: false,
    max_memory_restart: '{{ max_memory | default("1G") }}',
    env: {
      NODE_ENV: '{{ node_env | default("production") }}',
      PORT: {{ port | default(3000) }},
{% for key, val in env_vars.items() %}
      {{ key }}: '{{ val }}',
{% endfor %}
    },
    log_file: '/var/log/{{ app_name }}/combined.log',
    out_file: '/var/log/{{ app_name }}/out.log',
    error_file: '/var/log/{{ app_name }}/error.log',
    log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
  }]
};
"""

REMIX_ENV = """\
# Generated by DeployBot — {{ timestamp }}
NODE_ENV=production

{% if database_type == 'mysql' %}
DATABASE_URL=mysql://{{ db_user | default('root') }}:{{ db_password }}@localhost:3306/{{ db_name }}
{% elif database_type == 'postgres' %}
DATABASE_URL=postgresql://{{ db_user | default('postgres') }}:{{ db_password }}@localhost:5432/{{ db_name }}
{% endif %}

{% if shopify_api_key is defined %}
SHOPIFY_API_KEY={{ shopify_api_key }}
SHOPIFY_API_SECRET={{ shopify_api_secret }}
SHOPIFY_APP_URL=https://{{ domain }}/
SCOPES={{ shopify_scopes | default('read_products,write_products') }}
{% endif %}

{% if custom_vars is defined %}
{% for key, val in custom_vars.items() %}
{{ key }}={{ val }}
{% endfor %}
{% endif %}

SESSION_SECRET={{ session_secret }}
PORT={{ port | default(3000) }}
"""

NODE_ENV = """\
# Generated by DeployBot — {{ timestamp }}
NODE_ENV=production
PORT={{ port | default(3000) }}

{% if database_type is defined %}
DATABASE_URL={{ database_url }}
{% endif %}

{% for key, val in custom_vars.items() %}
{{ key }}={{ val }}
{% endfor %}
"""


_TEMPLATES = {
    "nginx_node": NGINX_NODE,
    "nginx_laravel": NGINX_LARAVEL,
    "nginx_static": NGINX_STATIC,
    "pm2_config": PM2_CONFIG,
    "remix_env": REMIX_ENV,
    "node_env": NODE_ENV,
}


class TemplateEngine:
    """Renders configuration files from Jinja2 templates."""

    def __init__(self, template_dir: str | None = None):
        if template_dir and Path(template_dir).exists():
            # Load from filesystem if directory provided
            self._env = Environment(
                loader=FileSystemLoader(template_dir),
                trim_blocks=True,
                lstrip_blocks=True,
            )
        else:
            self._env = Environment(
                loader=DictLoader(_TEMPLATES),
                trim_blocks=True,
                lstrip_blocks=True,
            )

    def render(self, template_name: str, context: dict[str, Any]) -> str:
        """Render a named template with the given context dict."""
        template = self._env.get_template(template_name)
        return template.render(**context)

    def render_string(self, template_str: str, context: dict[str, Any]) -> str:
        """Render an arbitrary Jinja2 string template."""
        template = self._env.from_string(template_str)
        return template.render(**context)

    def nginx_for_stack(self, stack: str, context: dict) -> str:
        """Return rendered NGINX config for a given stack type."""
        mapping = {
            "node": "nginx_node",
            "nodejs": "nginx_node",
            "remix": "nginx_node",
            "next": "nginx_node",
            "express": "nginx_node",
            "laravel": "nginx_laravel",
            "php": "nginx_laravel",
            "static": "nginx_static",
            "html": "nginx_static",
            "react": "nginx_static",
            "vue": "nginx_static",
        }
        template_key = mapping.get(stack.lower(), "nginx_node")
        return self.render(template_key, context)

    def env_for_stack(self, stack: str, context: dict) -> str:
        """Return rendered .env file for a given stack type."""
        import datetime
        context.setdefault("timestamp", datetime.datetime.utcnow().isoformat())
        context.setdefault("custom_vars", {})

        if stack.lower() in ("remix", "shopify"):
            return self.render("remix_env", context)
        return self.render("node_env", context)
